### ISSUE TITLE
理由いろいろ

### ISSUE THREAD

**Issue by kmuto** [takahashim/review-markup-sample#1]
> この`@<tt>{[nodisp]}`って何に使うんでしたっけ…。

献辞とか挿絵とかみたいに、紙面に文字は入れたくないけど目次には掲載したいというとき用ですね。とりあえず仮で入れておいてあとでフックで上書きするようなファイルでも使うことがあります。

> `@<tt>{[notoc]}`をつけると、見出しに数値が省かれるのに加え、目次にも表示されなくなります。使い方によっては便利だそうです（自分では使ったことないのでよく分からない）。

手元のだと練習問題とか、補足とか、ちょっと変わった見出し構造のがたまにあって、そういう場面だと使っていますね。あと、前付や付録などで下位レベルの見出しはEPUB目次に入れたくないとか。

> そのような場合、このサンプルのように、「`@<tt>{@}`」と「`@<tt>{<foo>{...\}}`」で分割するという技があります。

実はこういうときにも謎記法なら中身はエスケープ不要でリテラルになるので、`@<tt>|@<tt>{...}|` とか書けたりします。最近}が多いものは数式に限らずこの記法を使うことが多くなりました…

**Comment by takahashim** [comment]
ありがとうございます！　この内容を反映させればいいですかね。
あと`|〜|`とか`$〜$`は数式以外でもおすすめしていいんでしたっけ？（まだexperimentalな気持ちです）

**Comment by kmuto** [comment]
今`@<tt>`内に`}`が大量に登場する本を制作していて、フェンス記法がないと死ぬところでした、というくらいにすっかり使ってます…。

TeX組版系だと`@<raw>$|latex|\linebreak{}$`みたいなのも多用しますね。

**Comment by takahashim** [comment]
#2 で対応しました！
